/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class UsersPayslip extends javax.swing.JFrame {

    /**
     * Creates new form UsersPayslip
     */
    public UsersPayslip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField20 = new javax.swing.JTextField();
        SSSContribution1 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        PhilHealthContribution1 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        PagIBIG1 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        SelectDate1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        MotorPH1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField31 = new javax.swing.JTextField();
        EmployeeNumber1 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        FirstName1 = new javax.swing.JLabel();
        Total1 = new javax.swing.JLabel();
        LastName1 = new javax.swing.JLabel();
        Earnings1 = new javax.swing.JLabel();
        GrossPay1 = new javax.swing.JLabel();
        Position1 = new javax.swing.JLabel();
        BasicSalary1 = new javax.swing.JLabel();
        SSS1 = new javax.swing.JLabel();
        GSMR1 = new javax.swing.JLabel();
        PhilHealth1 = new javax.swing.JLabel();
        TIN1 = new javax.swing.JLabel();
        NetPay1 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        HR1 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        Allowances1 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        RiceSubsidy1 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        PhoneAllowance1 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        ClothingAllowance1 = new javax.swing.JLabel();
        GeneratePayslip1 = new javax.swing.JButton();
        jTextField38 = new javax.swing.JTextField();
        Deduction1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        SSSContribution = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        PhilHealthContribution = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        PagIBIG = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        SelectDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        MotorPH = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField16 = new javax.swing.JTextField();
        EmployeeNumber = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Earnings = new javax.swing.JLabel();
        GrossPay = new javax.swing.JLabel();
        Position = new javax.swing.JLabel();
        BasicSalary = new javax.swing.JLabel();
        SSS = new javax.swing.JLabel();
        GSMR = new javax.swing.JLabel();
        PhilHealth = new javax.swing.JLabel();
        TIN = new javax.swing.JLabel();
        NetPay = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        HR = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        Allowances = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        RiceSubsidy = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        PhoneAllowance = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        ClothingAllowance = new javax.swing.JLabel();
        GeneratePayslip = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        Deduction = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(232, 232, 232));

        SSSContribution1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SSSContribution1.setText("SSS Contribution :");

        jTextField21.setEditable(false);
        jTextField21.setBackground(new java.awt.Color(232, 232, 232));

        PhilHealthContribution1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PhilHealthContribution1.setText("PhilHealth Contribution : ");

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(232, 232, 232));
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });

        PagIBIG1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PagIBIG1.setText("Pag-IBIG Contribution :");

        jTextField23.setEditable(false);
        jTextField23.setBackground(new java.awt.Color(232, 232, 232));

        jTextField24.setEditable(false);
        jTextField24.setBackground(new java.awt.Color(232, 232, 232));
        jTextField24.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        SelectDate1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SelectDate1.setText("Select Date");

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        MotorPH1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        MotorPH1.setForeground(new java.awt.Color(255, 255, 255));
        MotorPH1.setText("Motor PH");

        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAYSLIP");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MotorPH1)
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MotorPH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(24, 24, 24))
        );

        jTextField25.setEditable(false);
        jTextField25.setBackground(new java.awt.Color(232, 232, 232));
        jTextField25.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField26.setEditable(false);
        jTextField26.setBackground(new java.awt.Color(232, 232, 232));
        jTextField26.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField27.setEditable(false);
        jTextField27.setBackground(new java.awt.Color(232, 232, 232));
        jTextField27.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField28.setBackground(new java.awt.Color(232, 232, 232));
        jTextField28.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });

        jTextField29.setBackground(new java.awt.Color(232, 232, 232));
        jTextField29.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField30.setEditable(false);
        jTextField30.setBackground(new java.awt.Color(232, 232, 232));
        jTextField30.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField31.setEditable(false);
        jTextField31.setBackground(new java.awt.Color(232, 232, 232));
        jTextField31.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        EmployeeNumber1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        EmployeeNumber1.setText("Employee Number :");

        jTextField32.setEditable(false);
        jTextField32.setBackground(new java.awt.Color(232, 232, 232));
        jTextField32.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        FirstName1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        FirstName1.setText("First Name : ");

        Total1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Total1.setText("TOTAL:");

        LastName1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        LastName1.setText("Last Name :");

        Earnings1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Earnings1.setText("EARNINGS");

        GrossPay1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        GrossPay1.setText("Gross Pay : ");

        Position1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Position1.setText("Position : ");

        BasicSalary1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BasicSalary1.setText("Basic Salary :");

        SSS1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SSS1.setText("SSS :");

        GSMR1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        GSMR1.setText("Gross Semi-Monthly Rate : ");

        PhilHealth1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PhilHealth1.setText("PhilHealth :");

        TIN1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TIN1.setText("TIN :");

        NetPay1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        NetPay1.setText("Net Pay :");

        jTextField33.setBackground(new java.awt.Color(232, 232, 232));
        jTextField33.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });

        HR1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        HR1.setText("Hourly Rate: ");

        jTextField34.setEditable(false);
        jTextField34.setBackground(new java.awt.Color(232, 232, 232));
        jTextField34.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        Allowances1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Allowances1.setText("ALLOWANCES");

        jTextField35.setEditable(false);
        jTextField35.setBackground(new java.awt.Color(232, 232, 232));
        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });

        RiceSubsidy1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RiceSubsidy1.setText("Rice Subsidy :");

        jTextField36.setEditable(false);
        jTextField36.setBackground(new java.awt.Color(232, 232, 232));

        PhoneAllowance1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PhoneAllowance1.setText("Phone Allowance :");

        jTextField37.setEditable(false);
        jTextField37.setBackground(new java.awt.Color(232, 232, 232));

        ClothingAllowance1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ClothingAllowance1.setText("Clothing Allowance :");

        GeneratePayslip1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        GeneratePayslip1.setText("GENERATE PAYSLIP");
        GeneratePayslip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePayslip1ActionPerformed(evt);
            }
        });

        jTextField38.setEditable(false);
        jTextField38.setBackground(new java.awt.Color(232, 232, 232));

        Deduction1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Deduction1.setText("DEDUCTIONS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(232, 232, 232));

        SSSContribution.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SSSContribution.setText("SSS Contribution :");

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(232, 232, 232));

        PhilHealthContribution.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PhilHealthContribution.setText("PhilHealth Contribution : ");

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(232, 232, 232));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        PagIBIG.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PagIBIG.setText("Pag-IBIG Contribution :");

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(232, 232, 232));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(232, 232, 232));
        jTextField9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        SelectDate.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SelectDate.setText("Select Date");

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        MotorPH.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        MotorPH.setForeground(new java.awt.Color(255, 255, 255));
        MotorPH.setText("Motor PH");

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PAYSLIP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MotorPH)
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MotorPH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(232, 232, 232));
        jTextField10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(232, 232, 232));
        jTextField11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(232, 232, 232));
        jTextField12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField13.setBackground(new java.awt.Color(232, 232, 232));
        jTextField13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jTextField14.setBackground(new java.awt.Color(232, 232, 232));
        jTextField14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(232, 232, 232));
        jTextField15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(232, 232, 232));
        jTextField16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        EmployeeNumber.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        EmployeeNumber.setText("Employee Number :");

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(232, 232, 232));
        jTextField17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        FirstName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        FirstName.setText("First Name : ");

        Total.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Total.setText("TOTAL:");

        LastName.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        LastName.setText("Last Name :");

        Earnings.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Earnings.setText("EARNINGS");

        GrossPay.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        GrossPay.setText("Gross Pay : ");

        Position.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Position.setText("Position : ");

        BasicSalary.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BasicSalary.setText("Basic Salary :");

        SSS.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SSS.setText("SSS :");

        GSMR.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        GSMR.setText("Gross Semi-Monthly Rate : ");

        PhilHealth.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PhilHealth.setText("PhilHealth :");

        TIN.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        TIN.setText("TIN :");

        NetPay.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        NetPay.setText("Net Pay :");

        jTextField18.setBackground(new java.awt.Color(232, 232, 232));
        jTextField18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        HR.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        HR.setText("Hourly Rate: ");

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(232, 232, 232));
        jTextField19.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N

        Allowances.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Allowances.setText("ALLOWANCES");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(232, 232, 232));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        RiceSubsidy.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        RiceSubsidy.setText("Rice Subsidy :");

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(232, 232, 232));

        PhoneAllowance.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        PhoneAllowance.setText("Phone Allowance :");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(232, 232, 232));

        ClothingAllowance.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ClothingAllowance.setText("Clothing Allowance :");

        GeneratePayslip.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        GeneratePayslip.setText("GENERATE PAYSLIP");
        GeneratePayslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePayslipActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(232, 232, 232));

        Deduction.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Deduction.setText("DEDUCTIONS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Total)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NetPay, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(19, 19, 19)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(EmployeeNumber)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Position, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(FirstName, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(53, 53, 53)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField4)
                                                .addComponent(jTextField3)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(SSS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(PhilHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TIN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(jTextField6)
                                        .addComponent(jTextField7)
                                        .addComponent(jTextField8))
                                    .addGap(5, 5, 5)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(GSMR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(RiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Allowances, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(27, 27, 27)
                                                    .addComponent(GrossPay))
                                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HR, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Deduction, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(PagIBIG, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(152, 152, 152))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(SSSContribution, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PhilHealthContribution))
                                                    .addGap(143, 143, 143)))
                                            .addComponent(Earnings, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(209, 209, 209)
                                        .addComponent(GeneratePayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SelectDate)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EmployeeNumber)
                                    .addComponent(SSS)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FirstName)
                                    .addComponent(PhilHealth)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LastName)
                                    .addComponent(TIN)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Position)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SelectDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Earnings)
                    .addComponent(Allowances))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BasicSalary)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RiceSubsidy)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(GSMR)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PhoneAllowance)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HR)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClothingAllowance)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Deduction)
                            .addComponent(Total))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSSContribution)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrossPay)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhilHealthContribution)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NetPay)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PagIBIG)
                            .addComponent(jTextField17))
                        .addGap(64, 64, 64)
                        .addComponent(GeneratePayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
    
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
     
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
           
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void GeneratePayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePayslipActionPerformed
       
    }//GEN-LAST:event_GeneratePayslipActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
      
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void GeneratePayslip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePayslip1ActionPerformed
        
    }//GEN-LAST:event_GeneratePayslip1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UsersPayslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Allowances;
    private javax.swing.JLabel Allowances1;
    private javax.swing.JLabel BasicSalary;
    private javax.swing.JLabel BasicSalary1;
    private javax.swing.JLabel ClothingAllowance;
    private javax.swing.JLabel ClothingAllowance1;
    private javax.swing.JLabel Deduction;
    private javax.swing.JLabel Deduction1;
    private javax.swing.JLabel Earnings;
    private javax.swing.JLabel Earnings1;
    private javax.swing.JLabel EmployeeNumber;
    private javax.swing.JLabel EmployeeNumber1;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel FirstName1;
    private javax.swing.JLabel GSMR;
    private javax.swing.JLabel GSMR1;
    private javax.swing.JButton GeneratePayslip;
    private javax.swing.JButton GeneratePayslip1;
    private javax.swing.JLabel GrossPay;
    private javax.swing.JLabel GrossPay1;
    private javax.swing.JLabel HR;
    private javax.swing.JLabel HR1;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastName1;
    private javax.swing.JLabel MotorPH;
    private javax.swing.JLabel MotorPH1;
    private javax.swing.JLabel NetPay;
    private javax.swing.JLabel NetPay1;
    private javax.swing.JLabel PagIBIG;
    private javax.swing.JLabel PagIBIG1;
    private javax.swing.JLabel PhilHealth;
    private javax.swing.JLabel PhilHealth1;
    private javax.swing.JLabel PhilHealthContribution;
    private javax.swing.JLabel PhilHealthContribution1;
    private javax.swing.JLabel PhoneAllowance;
    private javax.swing.JLabel PhoneAllowance1;
    private javax.swing.JLabel Position;
    private javax.swing.JLabel Position1;
    private javax.swing.JLabel RiceSubsidy;
    private javax.swing.JLabel RiceSubsidy1;
    private javax.swing.JLabel SSS;
    private javax.swing.JLabel SSS1;
    private javax.swing.JLabel SSSContribution;
    private javax.swing.JLabel SSSContribution1;
    private javax.swing.JLabel SelectDate;
    private javax.swing.JLabel SelectDate1;
    private javax.swing.JLabel TIN;
    private javax.swing.JLabel TIN1;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Total1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
